/**
 * Metacore IoT Object Storage API
 * Metacore Object Storage - IOT Core Services
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DevicesInfo { 
    batteryOperated?: boolean;
    hwVersion?: string;
    loraMac?: string;
    manufacturer?: string;
    serialNo?: string;
    status?: string;
    swVersion?: string;
}