/**
 * Metacore IoT Object Storage API
 * Metacore Object Storage - IOT Core Services
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DevicesId } from './devicesId';
import { PreferencesSensors } from './preferencesSensors';

export interface PreferencesWidgets { 
    deviceId?: DevicesId;
    sensors?: Array<PreferencesSensors>;
    type?: PreferencesWidgets.TypeEnum;
    uid: string;
}
export namespace PreferencesWidgets {
    export type TypeEnum = 'device' | 'events' | 'map' | 'singlestat' | 'weather_forecast';
    export const TypeEnum = {
        Device: 'device' as TypeEnum,
        Events: 'events' as TypeEnum,
        Map: 'map' as TypeEnum,
        Singlestat: 'singlestat' as TypeEnum,
        WeatherForecast: 'weather_forecast' as TypeEnum
    };
}