/**
 * Metacore IoT Object Storage API
 * Metacore Object Storage - IOT Core Services
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrganizationsId } from './organizationsId';
import { RegionsId } from './regionsId';
import { UsersId } from './usersId';

export interface Users { 
    id?: UsersId;
    address?: string;
    email: string;
    firstname: string;
    isActive?: boolean;
    lastname: string;
    mobilePhoneNumber?: number;
    organizationId?: OrganizationsId;
    photoUrl?: string;
    regionId?: RegionsId;
    role?: string;
}